apiVersion: v1
kind: Service
metadata:
  name: flask-redis-service
  labels:
    app: flask-redis
spec:
  selector:
    app: flask-redis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
