apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  selector:
    app: ingestion-app
  ports:
  - protocol: TCP
    port: 5555        # Service's internal port
    targetPort: 5555  # Pod's exposed port
  type: NodePort      # Change to ClusterIP if you don't need external access
